.default: &default
  before_script:
    - pip install -r requirements.dev.txt
  script:
    - black --check --diff .
    - flake8 .
    - mypy --ignore-missing-imports .
    - python setup.py test

test-3.8:
  image: python:3.8-slim-buster
  <<: *default

test-3.7:
  image: python:3.7-slim-buster
  <<: *default

test-3.6:
  image: python:3.6-slim-buster
  <<: *default
