.default: &default
  before_script:
    - pip install -r requirements.dev.txt
  script:
    - black --check --diff .
    - flake8 .
    - mypy --ignore-missing-imports .
    - python setup.py test

test-3.12:
  image: python:3.12-slim-bookworm
  <<: *default

test-3.11:
  image: python:3.11-slim-buster
  <<: *default

test-3.10:
  image: python:3.10-slim-buster
  <<: *default

test-3.9:
  image: python:3.9-slim-buster
  <<: *default

test-3.8:
  image: python:3.8-slim-buster
  <<: *default
